# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb6d0324a931f93c99cbfccdcd8c43bd65643602b7d0364525f689cfe558edbc5283ced2b7099027f8d903fbdd24abd82b2a8c8aa927a3b851a0ea61006b5b15

test:
  secret_key_base: 091509a7664099d32b8ae7c0a627a86e00566fced720c3499f21821280ad07f498b3055c2b09f24f5afb6fc6d8e1e89e2353993b6cca931ba18c3e5c40de54ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
